### PR TITLE
Let connect() method wait until there is an actual connection

### PR DESCRIPTION
**Pull request by dennis-tra**
With this snippet I ran into a race condition
```dart
  var remoteDevtools = RemoteDevToolsMiddleware('localhost:8000');

  final store = DevToolsStore<AppState>(
    appReducer,
    initialState: AppState.initialState(),
    middleware: []
      ..add( my middlewares )
      ..add(remoteDevtools),
  );
  remoteDevtools.store = store;

  await remoteDevtools.connect();

  store.dispatch(Action1());
  store.dispatch(Action2());
```
after the `await remoteDevtools.connect();` has resolved the connection is actually not yet established but it is in the `starting` state. The lead to my first dispatched actions not to appear in the Remote Dev Portal. The condition for forwarding actions is `this.status == RemoteDevToolsStatus.started` which was not the case yet.

This pull request waits until the remote dev tools have responded with `START` and then resolves the `connect()` functions.

### CODE REVIEW

**Comment by MichaelMarner** [comment]
LGTM. Would you be able to update the tests and make them pass? Looks like just updating the mocks to simulate receiving the START message from a server.

**Comment by dennis-tra** [comment]
@MichaelMarner I updated the tests 👍

**Comment by MichaelMarner** [comment]
Awesome, thanks for the contribution!

**Comment by MichaelMarner** [comment]
This is now live in 0.0.9 on pub.dev

**Comment by dennis-tra** [comment]
Perfect, thanks for merging :)

**Pull request merged**
